### ISSUE TITLE
Feature request: source request for 1337x api

### ISSUE THREAD

**Issue by Deaths-Asylum** [piplongrun/lmwt-kiss.bundle#17]
1337x.org has a nice api with more options for quality releases and streaming. would you implement this?

**Comment by Twoure** [comment]
This channel pulls all of it's content from [PrimeWire.ag](http://www.primewire.ag/), and follows [KISS](https://en.wikipedia.org/wiki/KISS_principle) logic.

1337x.org is a torrent streaming site, and is not a source for [PrimeWire](http://www.primewire.ag/) content.  I assume you're asking for a new channel, similar to the Plex [BitTorrent](https://forums.plex.tv/discussion/102253) channel.  To request a new channel, create a [new post](https://forums.plex.tv/post/discussion/plex-channels) within the Plex Channel forums starting with `[REQ]` _(i.e. [REQ] 1337x.org Channel)_.

I'm sorry but since 1337x.org is not a source for PrimeWire.ag, it cannot be used for this channel.

**Comment by Deaths-Asylum** [comment]
OK thanks for the info and I appreciate the response when the streams work it's great just looking for more details and reliability thinking it had to do with the site not the channel. Thank you for your help
