### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by faersya** [piplongrun/lmwt-kiss.bundle#18]
hihi. I've been using your plugin for a while now, but for whatever reason for the last week or so the plugin isn't working for me at all.  None of the sources load, but when I check the website for the same sources and links they work just fine.  I've kinda just dealt with it and looked for other apps that I could use on my plex server, but at this point this is and was the only reliable app out there.  Thanks!

**Comment by piplongrun** [comment]
Sorry, can't do or tell anything without log files.

**Comment by faersya** [comment]
So you close a ticket without at least giving me a chance to give you the information you needed? That's real professional.

**Comment by piplongrun** [comment]
>So you close a ticket without at least giving me a chance to give you the information you needed? That's real professional.

Yep, luckily I'm not a professional, just a volunteer trying to keep things up and running in my spare time. Users who post "Not working!!" topics without taking the time to at least add _some_ information to the topic can't be helped. "It used to work" is not the info I'm looking for, always add info about your setup, Plex client/server versions, your location in the world (since some countries block certain sites), and log files to get a useful response. You can always reopen tickets on Github, but I don't liek having useless, informationless tickets open.
